env:
  es2021: true
  node: true
  browser: true
extends:
  - 'airbnb-base'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/prefer-default-export: 'off'
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs ver
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-param-reassign: 0
